### ISSUE TITLE
oversea_stats这个接口返回的数据有问题，现在明显少了很多数据

### ISSUE THREAD

**Issue by yccool** [cumt-robin/wuhan_best_wishes#16]
现在疫情重点在国外，但是你这个接口返回的数据明显比外面新闻看到的数据少太多了，麻烦检查一下，然后现在丁香园也提供了国外疫情数据和国外疫情地图，能否一起抓出来，谢谢！

**Comment by cumt-robin** [comment]
@yccool 已经修复oversea_stats；国外疫情地图暂时还没加
